name: Release Open WebUI Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'kubernetes/helm/**'

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # The Helm job fails with *.tgz included in the .gitignore file because it packages the chart in .tgz format
      # This job allows us to comment that line out without changing the file 
      - name: Comment out *.tgz in .gitignore
        run: |
          sed -i '/\*.tgz/s/^/#/' .gitignore

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          skip_existing: true
          packages_with_index: true
          charts_dir: kubernetes/helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"